apiVersion: v1
kind: Service
metadata:
  name: daedalus-auth-service
  namespace: daedalus-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /status
spec:
  type: NodePort
  selector:
    app: daedalus-auth
  ports:
    - port: 80
      targetPort: 3000