apiVersion: apps/v1
kind: Deployment
metadata:
  name: daedalus-auth-deployment
  namespace: daedalus-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daedalus-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: daedalus-auth
    spec:
      affinity:
        # This ensures pods will land on separate hosts
        #podAntiAffinity:
        #  requiredDuringSchedulingIgnoredDuringExecution:
        #    - labelSelector:
        #        matchExpressions: [{ key: app, operator: In, values: [daedalus-auth] }]
        #      topologyKey: "kubernetes.io/hostname"
      containers:
        - name: daedalus-auth
          image: 869229378759.dkr.ecr.ap-northeast-1.amazonaws.com/daedalus-backend:daedalus-auth-latest
          # Minikube: Uncomment the below since Minikube will use local docker registry
          # imagePullPolicy: Never
          ports:
            - containerPort: 3000
              protocol: TCP