apiVersion: v1
kind: Service
metadata:
  name: daedalus-auth-service
  namespace: daedalus-backend
spec:
  type: NodePort
  selector:
    app: daedalus-auth
  ports:
    - port: 80
      targetPort: 3000