apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daedalus-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: daedalus.app
      http:
        paths:
          - path: /auth/(.*)
            pathType: Prefix
            backend:
              service:
                name: daedalus-auth-service
                port:
                  number: 80